name: Run C Program


on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GCC
      run: sudo apt-get install -y gcc

    - name: Compile C program
      run: gcc -o my_program your_program_name.c

    - name: Run C program
      run: ./my_program
